# Generated by Django 2.0.4 on 2018-05-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pages',
            name='data',
        ),
        migrations.DeleteModel(
            name='Langs',
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
